Vagrant.configure("2") do |config|

  config.vm.box = "precise32"

  config.vm.synced_folder "../", "/vagrant"

  config.vm.network "public_network"

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "400"]
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
    ansible.verbose = "v"
  end

end